name = "BoostedDarkMatter"
uuid = "df2efd42-2b3d-4a7c-9adc-000ef4355e7c"
authors = ["Chen Xia <xiachen@sjtu.edu.cn> and contributors"]
version = "0.0.1"

[deps]
DarkMatterProfiles = "48b3a478-c9fa-42f4-b737-e59b1d0562ca"
MultiQuad = "8fca5bbe-a785-4bb7-9793-c0c8ddca5d4b"
NumericalTools = "a0f06128-cd74-4043-ac90-c71291fe1646"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
